# Generated by Django 4.2.7 on 2023-11-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=256)),
                ('password', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
